### ISSUE TITLE
Лабораторная работа №5

### ISSUE THREAD

**Issue by evgerher** [evgerher/TRPO5#1]
Готов сделать остальные unit test'ы
@evgeny-p

**Comment by evgeny-p** [comment]
Замечания по текущему состоянию работы:

1. Два последовательных вызова `make` приводят к ошибке: `mkdir: cannot create directory ‘obj’: File exists`.
1. Почему-то коэффициенты целочисленные.
1. Вперемешку используются типы `float` и `double`.
1. Имена набора тестов и самого теста не соответствуют содержимому: `distance_suite` и `simple_test`.
1. В репозитории осознанно оставлен файл `root_test.h` с примерами?

**Comment by evgerher** [comment]
@evgeny-p 
Исправлено кроме 4, как называть тесты?
> В репозитории осознанно оставлен файл root_test.h с примерами?

По ошибке.

**Comment by evgeny-p** [comment]
> Исправлено кроме 4, как называть тесты?

  Что тестируем? Функцию нахождения корней квардарного уравнения. Исходя из этого и можно выбрать название набора, например: `quadratic_equation_suite`.

  Как называть каждый тест? Исходя из того, какой случай он покрывает. Тестируем случай с отсутствием корней из-за отрицательного дискриминанта? `negative_discriminant_test`. Тестируем случай с двумя корнями? `two_roots_test`. Руководствуйтесь здравым смыслом. Представьте, что отчет читает другой человек, не знающий код. Строгих правил нет.

> По ошибке.

Ок, удаляем.

После выполнения основной работы (покрытие тестами), можете поразбираться со следующим вопросом: почему в Вашем случае при запуске команды `make` каждый раз выполняется линковка, даже если изменений в проекте не было.

**Comment by evgerher** [comment]
Сделано.
@evgeny-p

**Comment by evgeny-p** [comment]
1. Не удален файл `root_test.h`.
1. Каждый тест получился неполным:
  1. Кажется, тесты `discriminant_test` и `one_root_test` можно объединить в один с проверкой всех вычисленных функцией значений.
  1. В тестах `two_roots_test` и `one_root_test` не проверяется главное: корни уравнения.
1. Покрытие тестами также неполное: как минимум, не проверяются случаи:
  1. a = 0, b ≠ 0
  1. a = 0, b = 0

**Comment by evgerher** [comment]
Обновлено
@evgeny-p

**Comment by evgeny-p** [comment]
Работу проверял на ветке `makefile`.

1. Тесты `discriminant_test` и `one_root_test` образуют один класс эквивалентности.
1. Не покрыт тестами случай a = 0, b = 0.
1. Не заметил при прошлых проверках: в файле `root.h` незачем подключать `math.h`.

Не требуется для исправления в рамках текущей работы, но стоит подумать в будущем:

1. Функция `solve` возвращает целых четыре значения: два корня, их количество и дискриминант. Причем делает это неконсистентно: часть результатов вычислений возвращается через out-параметры, часть — как возвращаемое значение функции. Возможно, это имеет смысл упростить.

1. Количество корней в качестве статуса вычислений усложняет код, если необходимо различить ситуации, когда корней нет из-за отрицательного дискриминанта или из-за нулевых коэффициентов.

1. Функцию `solve` можно упростить, используя [ранний возврат](http://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code).

**Comment by evgerher** [comment]
@evgeny-p 
Исправлено в соответсвии с вашими указаниями и собственными размышлениями)

**Comment by evgeny-p** [comment]
По ЛР5:

1. Константы для статуса определены локально в функции. Это делает их недоступными для клиентского кода. Как следствие, в вызывающем коде приходится использовать [magic numbers](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), что снижает читаемость и порождает зависимость от конкретных знаений этих констант.

1. Само приложение падает, т.к. ожидается, что значение указателя `status` будет ненулевым. Это повод либо уточнить спецификацию функции, либо обрабатывать случай, когда `status == NULL`, и покрыть этот вариант тестом.

1. Тесты компилируются с предупреждениями.

По ЛР6 еще нужно было в файл `README.md` в корне репозитория включить Status Image (см. документацию по travis ci).

В общем по работе с репозиторием:

1. Текущая топология истории излишне запутана. См. пример в разделе FAQ: https://gist.github.com/jbenet/ee6c9ac48068889b0912

1. Раз уж вернулись в ветку `master`, давайте в настройках репозитория сделаем ее веткой по умолчанию.

**Comment by evgerher** [comment]
1. Исправлено, магические числа - это интересно.
2. Создал вспомогательную переменную status в основной программе.
3. С чем мне сравнивать ничем не измененную структуру, как мне ее использовать?
4. Я запутался немного с git pull и поэтому вышла такая ерунда.
5. Исправлено

@evgeny-p

**Comment by evgeny-p** [comment]
1. Константы вынесены, но не туда. Сейчас они доступны только в тестах, но не в клиентском коде. Поскольку они являются частью интерфейса модуля roots, то и должны быть описаны в файле, который определяет интерфейс этого модуля. Интерфейс модуля определяется его заголовочным файлом.

1. > С чем мне сравнивать ничем не измененную структуру, как мне ее использовать?

  Простой вариант: если значения, хранящиеся в структуре, не определены (что логично в некоторых случаях), то можно не создавать объект этой структуры и не присваивать ему результат.

  Альтернативный вариант: можно явно указать компилятору (и разработчику), что переменная создана и не используется намеренно.

   ```c
   // Определим такой макрос
   #define UNUSED(x) (void)(x)

   // И в вызывающем коде
  answer = ...
  UNUSED(answer);
   ```

  Чаще похожие приемы используются для подавления предупреждений в случае неиспользуемых аргументов функции:
  ```c
   void foo(int bar) {
   }
  ```

  ```
  $ gcc -c -Wall -Wextra foo.c
  foo.c: In function ‘foo’:
  foo.c:1:14: warning: unused parameter ‘bar’ [-Wunused-parameter]
  void foo(int bar) {
  $
  ```

  Но:
  ```c
   #define UNUSED(x) (void)(x)
   
   void foo(int bar) {
       UNUSED(bar);
   }
  ```

  ```
  $ gcc -c -Wall -Wextra foo.c
  $
  ```
  Используется для того, чтобы сохранить в сигнатуре имя неиспользуемого параметра. Еще возможные варианты:
  ```c
  // Убираем имя параметра. Снижает читаемость.
  void foo(int);

  // Можно так, но субъективно тоже не очень удобно читать.
  void foo(int /* bar */);
  ```
  
1. Про Status Image. При копировании ссылки из Travis CI доступен выбор различных форматов. Нужен формат Markdown, и в этом случае `README.md` должно быть изображение со статусом, а не ссылка.

**Comment by evgerher** [comment]
Исправлено
@evgeny-p

**Comment by evgeny-p** [comment]
Принято.
